/**
 * Portfolio morning briefing (§agent) — the one-line opener the dashboard greets
 * the team with. Generated by the nightly refresh from already-stored data (no
 * fresh Google Ads pull), so the dash renders it instantly.
 *
 * It's the teaser: "conversions on Celiora fell to near zero — likely
 * payments/tracking, not the ads." Opening the account starts the full read.
 */
import Anthropic from "@anthropic-ai/sdk";
import { prisma } from "@/lib/db";
import { computeWindows } from "@/lib/diagnostics/windows";
import type { Signal } from "@/lib/diagnostics/signals";

const client = new Anthropic();

const CUR: Record<string, string> = { EUR: "€", USD: "$", GBP: "£", CZK: "Kč", PLN: "zł" };
const money = (n: number, cur: string) => `${cur}${Math.round(n).toLocaleString("en-GB")}`;

const BRIEF_SYSTEM = `You are a senior Google Ads specialist on our agency team. Looking at one account's data, write the OPENING LINE you'd send a teammate — the single most important thing you noticed and your best hypothesis for why.

Rules:
- ONE sentence, maybe two. This is a headline in a morning briefing, not a report.
- Lead with what changed and the number/trend ("conversions fell from ~40/wk to near zero over 10 days"), then your hypothesis ("— likely a payments or tracking break, not the ads").
- State the hypothesis as a hypothesis. If a ROAS looks too high OR too low it usually means a tracking problem — say so.
- If SPEND itself collapsed on a Shopping/PMax account, suspect Merchant Center (disapprovals/misrep), not bidding.
- No greeting, no "I noticed", no account name prefix, no markdown, no bullet points. Just the line. Be specific with real numbers.`;

interface DiagMetrics {
  source?: string;
  window?: { spend: number; conversions: number; conversionValue: number; days: number };
  commerce?: { orders: number; revenue: number; currency: string } | null;
  grossMarginPct?: number | null;
  signals?: Signal[];
}
function parseDiag(json: string): DiagMetrics | null {
  try { const m = JSON.parse(json) as DiagMetrics; return m?.source === "diagnostics" ? m : null; }
  catch { return null; }
}

const ymd = (daysAgo: number) => { const d = new Date(); d.setUTCDate(d.getUTCDate() - daysAgo); return d.toISOString().slice(0, 10); };

/**
 * Generate (and persist) the briefing for one account. Returns the stored text,
 * or null if the account has no usable data. Green/no-data accounts get a null
 * briefing (nothing to say).
 */
export async function generateAccountBriefing(accountId: string): Promise<{ text: string | null; status: string } | null> {
  const account = await prisma.account.findUnique({
    where: { id: accountId },
    select: { id: true, name: true, currency: true, grossMarginPercent: true },
  });
  if (!account) return null;
  const cur = CUR[account.currency] ?? `${account.currency} `;

  const recent = await prisma.accountStatus.findMany({
    where: { accountId }, orderBy: { computedAt: "desc" }, take: 6,
  });
  const st = recent.find(s => parseDiag(s.metrics));
  const diag = st ? parseDiag(st.metrics) : null;
  const status = (st?.status as string) ?? "unknown";

  // Green or no data → nothing worth opening the day with. Clear any stale line.
  if (status === "green" || status === "unknown" || !diag) {
    await prisma.account.update({
      where: { id: accountId },
      data: { briefing: null, briefingStatus: status, briefingAt: new Date() },
    }).catch(() => null);
    return { text: null, status };
  }

  // Multi-window trend from the stored spine (cheap; nightly already refreshed it).
  const since = ymd(91), end = ymd(1);
  const [mRows, oRows, ctxRow] = await Promise.all([
    prisma.metricDaily.findMany({ where: { accountId, date: { gte: since } }, select: { date: true, spend: true, clicks: true, conversions: true, conversionValue: true } }),
    prisma.orderDaily.findMany({ where: { accountId, date: { gte: since } }, select: { date: true, orders: true, revenue: true } }),
    prisma.clientContext.findUnique({ where: { accountId }, select: { targetRoasNote: true, breakEvenRoas: true, mainKpi: true } }).catch(() => null),
  ]);
  const perDay = new Map<string, { date: string; spend: number; clicks: number; conversions: number; conversionValue: number }>();
  for (const r of mRows) {
    const e = perDay.get(r.date) ?? { date: r.date, spend: 0, clicks: 0, conversions: 0, conversionValue: 0 };
    e.spend += r.spend; e.clicks += r.clicks; e.conversions += r.conversions; e.conversionValue += r.conversionValue;
    perDay.set(r.date, e);
  }
  const windows = computeWindows([...perDay.values()], oRows, end, diag.grossMarginPct ?? account.grossMarginPercent ?? null);

  const L: string[] = [`ACCOUNT: ${account.name} (currency ${cur}). Current status: ${status.toUpperCase()}.`];
  if (windows.some(w => w.spend > 0)) {
    L.push(`Windows (spend / ROAS / POAS${windows.some(w => w.orders != null) ? " / orders" : ""}):`);
    for (const w of windows) {
      L.push(`  ${w.days}d: ${money(w.spend, cur)} / ${w.roas != null ? w.roas.toFixed(2) : "—"} / ${w.poas != null ? w.poas.toFixed(2) : "—"}${w.orders != null ? ` / ${w.orders}` : ""}${w.partial ? " (partial)" : ""}`);
    }
  } else {
    L.push(`No spend in any window (7–90d) — likely paused or delivery blocked.`);
  }
  const problems = (diag.signals ?? []).filter(s => s.kind === "problem").slice(0, 3);
  if (problems.length) { L.push(`Detected issues:`); for (const s of problems) L.push(`  - ${s.detail}`); }
  if (ctxRow?.targetRoasNote) L.push(`Client target ROAS: ${ctxRow.targetRoasNote}`);
  if (ctxRow?.breakEvenRoas) L.push(`Break-even ROAS: ${ctxRow.breakEvenRoas.toFixed(2)}`);
  if (ctxRow?.mainKpi) L.push(`Client main KPI: ${ctxRow.mainKpi}`);

  const msg = await client.messages.create({
    model: "claude-sonnet-5",
    max_tokens: 200,
    system: BRIEF_SYSTEM,
    messages: [{ role: "user", content: L.join("\n") }],
  });
  const text = msg.content.filter((b): b is Anthropic.TextBlock => b.type === "text").map(b => b.text).join("").trim() || null;

  await prisma.account.update({
    where: { id: accountId },
    data: { briefing: text, briefingStatus: status, briefingAt: new Date() },
  }).catch(() => null);

  return { text, status };
}
