-- Portfolio morning briefing: a one-line agent opener per account, generated by
-- the nightly refresh so the dashboard greets the team with what it noticed.
-- Additive + idempotent.
ALTER TABLE "Account" ADD COLUMN IF NOT EXISTS "briefing" TEXT;
ALTER TABLE "Account" ADD COLUMN IF NOT EXISTS "briefingStatus" TEXT;
ALTER TABLE "Account" ADD COLUMN IF NOT EXISTS "briefingAt" TIMESTAMP(3);
